# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import __rayforce
else:
    import __rayforce

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def eval_str(str):
    r"""eval_str(lit_p str) -> obj_t"""
    return __rayforce.eval_str(str)

def i64(val):
    r"""i64(i64_t val) -> obj_t"""
    return __rayforce.i64(val)
TYPE_LIST = __rayforce.TYPE_LIST

TYPE_B8 = __rayforce.TYPE_B8

TYPE_U8 = __rayforce.TYPE_U8

TYPE_I16 = __rayforce.TYPE_I16

TYPE_I32 = __rayforce.TYPE_I32

TYPE_I64 = __rayforce.TYPE_I64

TYPE_SYMBOL = __rayforce.TYPE_SYMBOL

TYPE_DATE = __rayforce.TYPE_DATE

TYPE_TIME = __rayforce.TYPE_TIME

TYPE_TIMESTAMP = __rayforce.TYPE_TIMESTAMP

TYPE_F64 = __rayforce.TYPE_F64

TYPE_GUID = __rayforce.TYPE_GUID

TYPE_C8 = __rayforce.TYPE_C8

TYPE_ENUM = __rayforce.TYPE_ENUM

TYPE_MAPFILTER = __rayforce.TYPE_MAPFILTER

TYPE_MAPGROUP = __rayforce.TYPE_MAPGROUP

TYPE_MAPFD = __rayforce.TYPE_MAPFD

TYPE_MAPCOMMON = __rayforce.TYPE_MAPCOMMON

TYPE_MAPLIST = __rayforce.TYPE_MAPLIST

TYPE_PARTEDLIST = __rayforce.TYPE_PARTEDLIST

TYPE_PARTEDB8 = __rayforce.TYPE_PARTEDB8

TYPE_PARTEDU8 = __rayforce.TYPE_PARTEDU8

TYPE_PARTEDI16 = __rayforce.TYPE_PARTEDI16

TYPE_PARTEDI32 = __rayforce.TYPE_PARTEDI32

TYPE_PARTEDI64 = __rayforce.TYPE_PARTEDI64

TYPE_PARTEDDATE = __rayforce.TYPE_PARTEDDATE

TYPE_PARTEDTIME = __rayforce.TYPE_PARTEDTIME

TYPE_PARTEDTIMESTAMP = __rayforce.TYPE_PARTEDTIMESTAMP

TYPE_PARTEDF64 = __rayforce.TYPE_PARTEDF64

TYPE_PARTEDGUID = __rayforce.TYPE_PARTEDGUID

TYPE_PARTEDENUM = __rayforce.TYPE_PARTEDENUM

TYPE_TABLE = __rayforce.TYPE_TABLE

TYPE_DICT = __rayforce.TYPE_DICT

TYPE_LAMBDA = __rayforce.TYPE_LAMBDA

TYPE_UNARY = __rayforce.TYPE_UNARY

TYPE_BINARY = __rayforce.TYPE_BINARY

TYPE_VARY = __rayforce.TYPE_VARY

TYPE_TOKEN = __rayforce.TYPE_TOKEN

TYPE_NULL = __rayforce.TYPE_NULL

TYPE_ERROR = __rayforce.TYPE_ERROR

OK = __rayforce.OK

ERR_INIT = __rayforce.ERR_INIT

ERR_PARSE = __rayforce.ERR_PARSE

ERR_EVAL = __rayforce.ERR_EVAL

ERR_FORMAT = __rayforce.ERR_FORMAT

ERR_TYPE = __rayforce.ERR_TYPE

ERR_LENGTH = __rayforce.ERR_LENGTH

ERR_ARITY = __rayforce.ERR_ARITY

ERR_INDEX = __rayforce.ERR_INDEX

ERR_HEAP = __rayforce.ERR_HEAP

ERR_IO = __rayforce.ERR_IO

ERR_SYS = __rayforce.ERR_SYS

ERR_OS = __rayforce.ERR_OS

ERR_NOT_FOUND = __rayforce.ERR_NOT_FOUND

ERR_NOT_EXIST = __rayforce.ERR_NOT_EXIST

ERR_NOT_IMPLEMENTED = __rayforce.ERR_NOT_IMPLEMENTED

ERR_NOT_SUPPORTED = __rayforce.ERR_NOT_SUPPORTED

ERR_STACK_OVERFLOW = __rayforce.ERR_STACK_OVERFLOW

ERR_RAISE = __rayforce.ERR_RAISE

ERR_UNKNOWN = __rayforce.ERR_UNKNOWN

class obj_t(object):
    r"""Proxy of C obj_t struct."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    mmod = property(__rayforce.obj_t_mmod_get, __rayforce.obj_t_mmod_set, doc=r"""mmod : u8_t""")
    order = property(__rayforce.obj_t_order_get, __rayforce.obj_t_order_set, doc=r"""order : u8_t""")
    type = property(__rayforce.obj_t_type_get, __rayforce.obj_t_type_set, doc=r"""type : i8_t""")
    attrs = property(__rayforce.obj_t_attrs_get, __rayforce.obj_t_attrs_set, doc=r"""attrs : u8_t""")
    rc = property(__rayforce.obj_t_rc_get, __rayforce.obj_t_rc_set, doc=r"""rc : u32_t""")
    b8 = property(__rayforce.obj_t_b8_get, __rayforce.obj_t_b8_set, doc=r"""b8 : b8_t""")
    u8 = property(__rayforce.obj_t_u8_get, __rayforce.obj_t_u8_set, doc=r"""u8 : u8_t""")
    c8 = property(__rayforce.obj_t_c8_get, __rayforce.obj_t_c8_set, doc=r"""c8 : c8_t""")
    i16 = property(__rayforce.obj_t_i16_get, __rayforce.obj_t_i16_set, doc=r"""i16 : i16_t""")
    i32 = property(__rayforce.obj_t_i32_get, __rayforce.obj_t_i32_set, doc=r"""i32 : i32_t""")
    i64 = property(__rayforce.obj_t_i64_get, __rayforce.obj_t_i64_set, doc=r"""i64 : i64_t""")
    f64 = property(__rayforce.obj_t_f64_get, __rayforce.obj_t_f64_set, doc=r"""f64 : f64_t""")
    obj = property(__rayforce.obj_t_obj_get, __rayforce.obj_t_obj_set, doc=r"""obj : p.struct obj_t""")
    len = property(__rayforce.obj_t_len_get, __rayforce.obj_t_len_set, doc=r"""len : u64_t""")

    def __init__(self):
        r"""__init__(obj_t self) -> obj_t"""
        __rayforce.obj_t_swiginit(self, __rayforce.new_obj_t())
    __swig_destroy__ = __rayforce.delete_obj_t

# Register obj_t in __rayforce:
__rayforce.obj_t_swigregister(obj_t)
cvar = __rayforce.cvar
NULL_GUID = cvar.NULL_GUID


def version():
    r"""version() -> u8_t"""
    return __rayforce.version()

def null(type):
    r"""null(i8_t type) -> obj_t"""
    return __rayforce.null(type)

def nullv(type, len):
    r"""nullv(i8_t type, u64_t len) -> obj_t"""
    return __rayforce.nullv(type, len)

def atom(type):
    r"""atom(i8_t type) -> obj_t"""
    return __rayforce.atom(type)

def vn_list(*args):
    r"""vn_list(u64_t len) -> obj_t"""
    return __rayforce.vn_list(*args)

def vector(type, len):
    r"""vector(i8_t type, u64_t len) -> obj_t"""
    return __rayforce.vector(type, len)

def vn_symbol(*args):
    r"""vn_symbol(u64_t len) -> obj_t"""
    return __rayforce.vn_symbol(*args)

def b8(val):
    r"""b8(b8_t val) -> obj_t"""
    return __rayforce.b8(val)

def u8(val):
    r"""u8(u8_t val) -> obj_t"""
    return __rayforce.u8(val)

def c8(c):
    r"""c8(c8_t c) -> obj_t"""
    return __rayforce.c8(c)

def i16(val):
    r"""i16(i16_t val) -> obj_t"""
    return __rayforce.i16(val)

def i32(val):
    r"""i32(i32_t val) -> obj_t"""
    return __rayforce.i32(val)

def f64(val):
    r"""f64(f64_t val) -> obj_t"""
    return __rayforce.f64(val)

def symbol(ptr, len):
    r"""symbol(lit_p ptr, u64_t len) -> obj_t"""
    return __rayforce.symbol(ptr, len)

def symboli64(id):
    r"""symboli64(i64_t id) -> obj_t"""
    return __rayforce.symboli64(id)

def adate(val):
    r"""adate(i32_t val) -> obj_t"""
    return __rayforce.adate(val)

def atime(val):
    r"""atime(i32_t val) -> obj_t"""
    return __rayforce.atime(val)

def timestamp(val):
    r"""timestamp(i64_t val) -> obj_t"""
    return __rayforce.timestamp(val)

def guid(buf):
    r"""guid(guid_t const buf) -> obj_t"""
    return __rayforce.guid(buf)

def vn_c8(*args):
    r"""vn_c8(lit_p fmt) -> obj_t"""
    return __rayforce.vn_c8(*args)

def enumerate(sym, vec):
    r"""enumerate(obj_t sym, obj_t vec) -> obj_t"""
    return __rayforce.enumerate(sym, vec)

def anymap(sym, vec):
    r"""anymap(obj_t sym, obj_t vec) -> obj_t"""
    return __rayforce.anymap(sym, vec)

def table(keys, vals):
    r"""table(obj_t keys, obj_t vals) -> obj_t"""
    return __rayforce.table(keys, vals)

def dict(keys, vals):
    r"""dict(obj_t keys, obj_t vals) -> obj_t"""
    return __rayforce.dict(keys, vals)

def clone_obj(obj):
    r"""clone_obj(obj_t obj) -> obj_t"""
    return __rayforce.clone_obj(obj)

def copy_obj(obj):
    r"""copy_obj(obj_t obj) -> obj_t"""
    return __rayforce.copy_obj(obj)

def cow_obj(obj):
    r"""cow_obj(obj_t obj) -> obj_t"""
    return __rayforce.cow_obj(obj)

def rc_obj(obj):
    r"""rc_obj(obj_t obj) -> u32_t"""
    return __rayforce.rc_obj(obj)

def error(*args):
    r"""error(i8_t code, lit_p fmt) -> obj_t"""
    return __rayforce.error(*args)

def drop_obj(obj):
    r"""drop_obj(obj_t obj) -> nil_t"""
    return __rayforce.drop_obj(obj)

def drop_raw(ptr):
    r"""drop_raw(raw_p ptr) -> nil_t"""
    return __rayforce.drop_raw(ptr)

def is_null(obj):
    r"""is_null(obj_t obj) -> b8_t"""
    return __rayforce.is_null(obj)

def type_name(tp):
    r"""type_name(i8_t tp) -> str_p"""
    return __rayforce.type_name(tp)

def push_raw(obj, val):
    r"""push_raw(obj_p * obj, raw_p val) -> obj_t"""
    return __rayforce.push_raw(obj, val)

def push_obj(obj, val):
    r"""push_obj(obj_p * obj, obj_t val) -> obj_t"""
    return __rayforce.push_obj(obj, val)

def push_sym(obj, str):
    r"""push_sym(obj_p * obj, lit_p str) -> obj_t"""
    return __rayforce.push_sym(obj, str)

def append_list(obj, vals):
    r"""append_list(obj_p * obj, obj_t vals) -> obj_t"""
    return __rayforce.append_list(obj, vals)

def unify_list(obj):
    r"""unify_list(obj_p * obj) -> obj_t"""
    return __rayforce.unify_list(obj)

def pop_obj(obj):
    r"""pop_obj(obj_p * obj) -> obj_t"""
    return __rayforce.pop_obj(obj)

def remove_idx(obj, idx):
    r"""remove_idx(obj_p * obj, i64_t idx) -> obj_t"""
    return __rayforce.remove_idx(obj, idx)

def remove_ids(obj, ids, len):
    r"""remove_ids(obj_p * obj, i64_t [] ids, u64_t len) -> obj_t"""
    return __rayforce.remove_ids(obj, ids, len)

def remove_obj(obj, idx):
    r"""remove_obj(obj_p * obj, obj_t idx) -> obj_t"""
    return __rayforce.remove_obj(obj, idx)

def ins_raw(obj, idx, val):
    r"""ins_raw(obj_p * obj, i64_t idx, raw_p val) -> obj_t"""
    return __rayforce.ins_raw(obj, idx, val)

def ins_obj(obj, idx, val):
    r"""ins_obj(obj_p * obj, i64_t idx, obj_t val) -> obj_t"""
    return __rayforce.ins_obj(obj, idx, val)

def ins_sym(obj, idx, str):
    r"""ins_sym(obj_p * obj, i64_t idx, lit_p str) -> obj_t"""
    return __rayforce.ins_sym(obj, idx, str)

def at_idx(obj, idx):
    r"""at_idx(obj_t obj, i64_t idx) -> obj_t"""
    return __rayforce.at_idx(obj, idx)

def at_ids(obj, ids, len):
    r"""at_ids(obj_t obj, i64_t [] ids, u64_t len) -> obj_t"""
    return __rayforce.at_ids(obj, ids, len)

def at_obj(obj, idx):
    r"""at_obj(obj_t obj, obj_t idx) -> obj_t"""
    return __rayforce.at_obj(obj, idx)

def at_sym(obj, str, len):
    r"""at_sym(obj_t obj, lit_p str, u64_t len) -> obj_t"""
    return __rayforce.at_sym(obj, str, len)

def str_from_symbol(id):
    r"""str_from_symbol(i64_t id) -> str_p"""
    return __rayforce.str_from_symbol(id)

def zero_obj(obj):
    r"""zero_obj(obj_t obj) -> nil_t"""
    return __rayforce.zero_obj(obj)

def set_idx(obj, idx, val):
    r"""set_idx(obj_p * obj, i64_t idx, obj_t val) -> obj_t"""
    return __rayforce.set_idx(obj, idx, val)

def set_ids(obj, ids, len, vals):
    r"""set_ids(obj_p * obj, i64_t [] ids, u64_t len, obj_t vals) -> obj_t"""
    return __rayforce.set_ids(obj, ids, len, vals)

def set_obj(obj, idx, val):
    r"""set_obj(obj_p * obj, obj_t idx, obj_t val) -> obj_t"""
    return __rayforce.set_obj(obj, idx, val)

def rc_sync_get():
    r"""rc_sync_get() -> b8_t"""
    return __rayforce.rc_sync_get()

def rc_sync_set(on):
    r"""rc_sync_set(b8_t on) -> nil_t"""
    return __rayforce.rc_sync_set(on)

def resize_obj(obj, len):
    r"""resize_obj(obj_p * obj, u64_t len) -> obj_t"""
    return __rayforce.resize_obj(obj, len)

def find_raw(obj, val):
    r"""find_raw(obj_t obj, raw_p val) -> i64_t"""
    return __rayforce.find_raw(obj, val)

def find_obj(obj, val):
    r"""find_obj(obj_t obj, obj_t val) -> i64_t"""
    return __rayforce.find_obj(obj, val)

def find_sym(obj, str):
    r"""find_sym(obj_t obj, lit_p str) -> i64_t"""
    return __rayforce.find_sym(obj, str)

def cast_obj(type, obj):
    r"""cast_obj(i8_t type, obj_t obj) -> obj_t"""
    return __rayforce.cast_obj(type, obj)

def cmp_obj(a, b):
    r"""cmp_obj(obj_t a, obj_t b) -> i32_t"""
    return __rayforce.cmp_obj(a, b)

def ser_obj(obj):
    r"""ser_obj(obj_t obj) -> obj_t"""
    return __rayforce.ser_obj(obj)

def de_obj(buf):
    r"""de_obj(obj_t buf) -> obj_t"""
    return __rayforce.de_obj(buf)

def parse_str(str):
    r"""parse_str(lit_p str) -> obj_t"""
    return __rayforce.parse_str(str)

def eval_obj(obj):
    r"""eval_obj(obj_t obj) -> obj_t"""
    return __rayforce.eval_obj(obj)

def try_obj(obj, ctch):
    r"""try_obj(obj_t obj, obj_t ctch) -> obj_t"""
    return __rayforce.try_obj(obj, ctch)

def ray_init():
    r"""ray_init() -> i32_t"""
    return __rayforce.ray_init()

def ray_clean():
    r"""ray_clean() -> nil_t"""
    return __rayforce.ray_clean()

