# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rayforce
else:
    import _rayforce

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


TYPE_LIST = _rayforce.TYPE_LIST
TYPE_B8 = _rayforce.TYPE_B8
TYPE_U8 = _rayforce.TYPE_U8
TYPE_I64 = _rayforce.TYPE_I64
TYPE_F64 = _rayforce.TYPE_F64
TYPE_SYMBOL = _rayforce.TYPE_SYMBOL
TYPE_TIMESTAMP = _rayforce.TYPE_TIMESTAMP
TYPE_GUID = _rayforce.TYPE_GUID
TYPE_CHAR = _rayforce.TYPE_CHAR
TYPE_ENUM = _rayforce.TYPE_ENUM
TYPE_ANYMAP = _rayforce.TYPE_ANYMAP
TYPE_FILTERMAP = _rayforce.TYPE_FILTERMAP
TYPE_GROUPMAP = _rayforce.TYPE_GROUPMAP
TYPE_TABLE = _rayforce.TYPE_TABLE
TYPE_DICT = _rayforce.TYPE_DICT
TYPE_LAMBDA = _rayforce.TYPE_LAMBDA
TYPE_UNARY = _rayforce.TYPE_UNARY
TYPE_BINARY = _rayforce.TYPE_BINARY
TYPE_VARY = _rayforce.TYPE_VARY
TYPE_NULL = _rayforce.TYPE_NULL
TYPE_ERROR = _rayforce.TYPE_ERROR
OK = _rayforce.OK
ERR_INIT = _rayforce.ERR_INIT
ERR_PARSE = _rayforce.ERR_PARSE
ERR_EVAL = _rayforce.ERR_EVAL
ERR_FORMAT = _rayforce.ERR_FORMAT
ERR_TYPE = _rayforce.ERR_TYPE
ERR_LENGTH = _rayforce.ERR_LENGTH
ERR_ARITY = _rayforce.ERR_ARITY
ERR_INDEX = _rayforce.ERR_INDEX
ERR_HEAP = _rayforce.ERR_HEAP
ERR_IO = _rayforce.ERR_IO
ERR_SYS = _rayforce.ERR_SYS
ERR_NOT_FOUND = _rayforce.ERR_NOT_FOUND
ERR_NOT_EXIST = _rayforce.ERR_NOT_EXIST
ERR_NOT_IMPLEMENTED = _rayforce.ERR_NOT_IMPLEMENTED
ERR_NOT_SUPPORTED = _rayforce.ERR_NOT_SUPPORTED
ERR_STACK_OVERFLOW = _rayforce.ERR_STACK_OVERFLOW
ERR_RAISE = _rayforce.ERR_RAISE
ERR_UNKNOWN = _rayforce.ERR_UNKNOWN
class guid_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    buf = property(_rayforce.guid_t_buf_get, _rayforce.guid_t_buf_set)

    def __init__(self):
        _rayforce.guid_t_swiginit(self, _rayforce.new_guid_t())
    __swig_destroy__ = _rayforce.delete_guid_t

# Register guid_t in _rayforce:
_rayforce.guid_t_swigregister(guid_t)

class obj_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    mmod = property(_rayforce.obj_t_mmod_get, _rayforce.obj_t_mmod_set)
    refc = property(_rayforce.obj_t_refc_get, _rayforce.obj_t_refc_set)
    type = property(_rayforce.obj_t_type_get, _rayforce.obj_t_type_set)
    attrs = property(_rayforce.obj_t_attrs_get, _rayforce.obj_t_attrs_set)
    rc = property(_rayforce.obj_t_rc_get, _rayforce.obj_t_rc_set)
    b8 = property(_rayforce.obj_t_b8_get, _rayforce.obj_t_b8_set)
    u8 = property(_rayforce.obj_t_u8_get, _rayforce.obj_t_u8_set)
    vchar = property(_rayforce.obj_t_vchar_get, _rayforce.obj_t_vchar_set)
    i64 = property(_rayforce.obj_t_i64_get, _rayforce.obj_t_i64_set)
    f64 = property(_rayforce.obj_t_f64_get, _rayforce.obj_t_f64_set)
    obj = property(_rayforce.obj_t_obj_get, _rayforce.obj_t_obj_set)
    len = property(_rayforce.obj_t_len_get, _rayforce.obj_t_len_set)

    def __init__(self):
        _rayforce.obj_t_swiginit(self, _rayforce.new_obj_t())
    __swig_destroy__ = _rayforce.delete_obj_t

# Register obj_t in _rayforce:
_rayforce.obj_t_swigregister(obj_t)


def version():
    return _rayforce.version()

def null(type):
    return _rayforce.null(type)

def nullv(type, len):
    return _rayforce.nullv(type, len)

def atom(type):
    return _rayforce.atom(type)

def list(len):
    return _rayforce.list(len)

def vn_list(*args):
    return _rayforce.vn_list(*args)

def vector(type, len):
    return _rayforce.vector(type, len)

def vn_symbol(*args):
    return _rayforce.vn_symbol(*args)

def b8(val):
    return _rayforce.b8(val)

def u8(val):
    return _rayforce.u8(val)

def i64(val):
    return _rayforce.i64(val)

def f64(val):
    return _rayforce.f64(val)

def symbol(ptr):
    return _rayforce.symbol(ptr)

def symboli64(id):
    return _rayforce.symboli64(id)

def timestamp(val):
    return _rayforce.timestamp(val)

def guid(buf):
    return _rayforce.guid(buf)

def vchar(c):
    return _rayforce.vchar(c)

def string(len):
    return _rayforce.string(len)

def vn_string(*args):
    return _rayforce.vn_string(*args)

def venum(sym, vec):
    return _rayforce.venum(sym, vec)

def anymap(sym, vec):
    return _rayforce.anymap(sym, vec)

def table(keys, vals):
    return _rayforce.table(keys, vals)

def dict(keys, vals):
    return _rayforce.dict(keys, vals)

def clone_obj(obj):
    return _rayforce.clone_obj(obj)

def copy_obj(obj):
    return _rayforce.copy_obj(obj)

def cow_obj(obj):
    return _rayforce.cow_obj(obj)

def rc_obj(obj):
    return _rayforce.rc_obj(obj)

def error(*args):
    return _rayforce.error(*args)

def drop_obj(obj):
    return _rayforce.drop_obj(obj)

def drop_raw(ptr):
    return _rayforce.drop_raw(ptr)

def is_null(obj):
    return _rayforce.is_null(obj)

def type_name(tp):
    return _rayforce.type_name(tp)

def push_raw(obj, val):
    return _rayforce.push_raw(obj, val)

def push_obj(obj, val):
    return _rayforce.push_obj(obj, val)

def push_sym(obj, str):
    return _rayforce.push_sym(obj, str)

def append_list(obj, vals):
    return _rayforce.append_list(obj, vals)

def pop_obj(obj):
    return _rayforce.pop_obj(obj)

def ins_raw(obj, idx, val):
    return _rayforce.ins_raw(obj, idx, val)

def ins_obj(obj, idx, val):
    return _rayforce.ins_obj(obj, idx, val)

def ins_sym(obj, idx, str):
    return _rayforce.ins_sym(obj, idx, str)

def at_idx(obj, idx):
    return _rayforce.at_idx(obj, idx)

def at_ids(obj, ids, len):
    return _rayforce.at_ids(obj, ids, len)

def at_obj(obj, idx):
    return _rayforce.at_obj(obj, idx)

def at_sym(obj, str):
    return _rayforce.at_sym(obj, str)

def strof_sym(id):
    return _rayforce.strof_sym(id)

def strof_obj(obj):
    return _rayforce.strof_obj(obj)

def zero_obj(obj):
    return _rayforce.zero_obj(obj)

def set_idx(obj, idx, val):
    return _rayforce.set_idx(obj, idx, val)

def set_ids(obj, ids, len, vals):
    return _rayforce.set_ids(obj, ids, len, vals)

def set_obj(obj, idx, val):
    return _rayforce.set_obj(obj, idx, val)

def resize_obj(obj, len):
    return _rayforce.resize_obj(obj, len)

def find_raw(obj, val):
    return _rayforce.find_raw(obj, val)

def find_obj(obj, val):
    return _rayforce.find_obj(obj, val)

def find_sym(obj, str):
    return _rayforce.find_sym(obj, str)

def cast_obj(type, obj):
    return _rayforce.cast_obj(type, obj)

def cmp_obj(a, b):
    return _rayforce.cmp_obj(a, b)

def ser_obj(obj):
    return _rayforce.ser_obj(obj)

def de_obj(buf):
    return _rayforce.de_obj(buf)

def parse_str(fd, str, file):
    return _rayforce.parse_str(fd, str, file)

def eval_str(str):
    return _rayforce.eval_str(str)

def eval_obj(obj):
    return _rayforce.eval_obj(obj)

def try_obj(obj, ctch):
    return _rayforce.try_obj(obj, ctch)

def ray_init():
    return _rayforce.ray_init()

def ray_clean():
    return _rayforce.ray_clean()


